### ISSUE TITLE
Support events catching and  dynamic changing of content 

### ISSUE THREAD

**Issue by Joetib** [sayanarijit/htmldoom#39]
Although not asking that this be as big as react or how anvil renders pages,  it will be easy if the framework can support catching events and performing dynamic content generation without requiring javascript for basic functionality.

**Comment by sayanarijit** [comment]
Could you give few examples of the proposal so that I understand it correctly?

FYI, this is a server side library so it doesn't work on frontend. To target frontend we either need to compile the Python code in JavaScript or WebAssembly or somehow run a Python interpreter in the browser (without compromising on performance). I'm doing some digging into these options in my free time but none looks achievable as of current state (although efforts are going on). Or if you have some other ideas, feel free to share.

**Comment by sayanarijit** [comment]
Not sure... might be possible with Transcrypt.
Ref: https://github.com/QQuick/Transcrypt/issues/653

**Comment by sayanarijit** [comment]
Closing this as there wasn't any response/interest in https://github.com/QQuick/Transcrypt/issues/653
